# Generated by Django 3.2.19 on 2026-01-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20251217_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('theater', 'seat_number')},
        ),
    ]
